language: python
python:
  - 2.7
  - 3.6
sudo: false
install:
  - pip install tox
  - pip install codecov
script:
  - tox -v -e py
after_success:
    - codecov
notifications:
  email:
    on_success: always
    on_failure: always
