language: python
python:
  - 2.7
  - 3.6
sudo: false
install:
  - pip install tox
  - pip install codecov
script:
  - tox -v -e py
after_success:
    - codecov
notifications:
  email:
    on_success: always
    on_failure: always
deploy:
  provider: pypi
  on:
    branch: release
  distributions: sdist
  user: b3b
  password:
    secure: O8gPTgQoevUZhAlhuVlVO7WTF6hLC/6Eaq3DHDx3L+7SsPaPedRgqlhQnywSsJsdTYcHWi5AtvAoDpyvIBgEqE7XT7Hb2EqSpM0nEszXKqd0rkaK6ufPk72ExuNRIaZPwNzmNjKPTalw1kvtz+4lSY3jgs0CWYFNA8dvCcLU+QzMW+TIStjcPcvf3qXgdjwlURn0j6L7KqJ22bKtQze+pZFOAifMB72WxSSsbghpnMG4uHmVNiLBQkFQYMUENcikfjL7XkqjUv3HFSmA6HvkkVmke+P69GNGXbY/wC6ZFiKwYb018/PYTqQiM7Cj/tAXISMh4saTwWMRCvSUCD0zXZX42Tw2zSsdALpSCzEiqgfzX/BR+CkgUi1p3ffaJNanoix4N0hIAM+DOo3UE0gZg2YrA4JiSptAj3IxYith1aKwuCkJFNiDo71voH9MyqzXEG3fWiarpXkEfG39L9e6sb5V4mHTUT+hSBVmoRb0LHRlnQ/2rjI9PAiydznkKmZvlRu9HnkMIXhkxuQPWKis9gq48xCShqGMK6Pr+aPknh3e6s/Jgqrrpmh24at4ER38Lar4VCHpedJedLg+JAalvpdrAWQsKdXlSt+jZjj/Y5EdtRWiSvkUQhJqUCLrogSPcAVogjCkP969WlIo9jasbOv2S7GxZzao0pB/0rFIpzg=
